services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: REPLACE_WITH_YOUR_USERNAME
      POSTGRES_PASSWORD: REPLACE_WITH_YOUR_PASSWORD
      POSTGRES_DB: REPLACE_WITH_YOUR_DATABASE_NAME
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
